---
- name: Create user
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create user
      user:
        name: sepehr2
        password: "u.SEhAv5/Lv4c"
        shell: /bin/bash
        createhome: yes
        group: sudo
    - name: Deploy SSH Key
      authorized_key: user=sepehr2
        key="{{ lookup('file', './id_rsa.pub') }}"
        state=present
